config/routes.rb
Rails.application.eager_load! if Rails.env.development?

class ActionDispatch::Routing::Mapper
  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end
end

Peatio::Application.routes.draw do
  use_doorkeeper

  root 'welcome#index'

  if Rails.env.development?
    mount MailsViewer::Engine => '/mails'
  end

  get '/signin' => 'sessions#new', :as => :signin
  get '/privacy-policy' => 'statics#privacy', :as => :privacy
  get '/terms-of-use' => 'statics#terms', :as => :terms
  get '/signup' => 'identities#new', :as => :signup
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure', :as => :failure
  match '/auth/:provider/callback' => 'sessions#create', via: [:get, :post]
  post '/sendcode' => 'identities#sendcode', :as => :sendcode
  


  resource :member, :only => [:edit, :update]
  resource :identity, :only => [:edit, :update]

  namespace :verify do
    resource :sms_auth,    only: [:show, :update]
    resource :google_auth, only: [:show, :update, :edit, :destroy]
  end

  namespace :authentications do
    resources :emails, only: [:new, :create]
    resources :identities, only: [:new, :create]
    resource :weibo_accounts, only: [:destroy]
  end

  scope :constraints => { id: /[a-zA-Z0-9]{32}/ } do
    resources :reset_passwords
    resources :activations, only: [:new, :edit, :update]
  end

  get '/documents/api_v2'
  get '/documents/websocket_api'
  get '/documents/oauth'
  resources :documents, only: [:show]
  resources :two_factors, only: [:show, :index, :update]

  scope module: :private do
    resource  :id_document, only: [:edit, :update]

    resources :settings, only: [:index]
    resources :api_tokens do
      member do
        delete :unbind
      end
    end

    resources :fund_sources, only: [:create, :update, :destroy]

    resources :funds, only: [:index] do
      collection do
        post :gen_address
      end
    end

    namespace :deposits do
      Deposit.descendants.each do |d|
        resources d.resource_name do
          collection do
            post :gen_address
          end
        end
      end
    end

    namespace :withdraws do
      Withdraw.descendants.each do |w|
        resources w.resource_name
      end
    end

    resources :account_versions, :only => :index

    resources :exchange_assets, :controller => 'assets' do
      member do
        get :partial_tree
      end
    end

    get '/history/orders' => 'history#orders', as: :order_history
    get '/history/trades' => 'history#trades', as: :trade_history
    get '/history/account' => 'history#account', as: :account_history
    get '/history/access' => 'history#access', as: :access_history
    get '/history/affiliate' => 'history#affiliate', as: :affiliate_history
    get '/history/commission' => 'history#commission', as: :commission_history
    get '/history/offer' => 'history#offer', as: :offer_special
    get '/support/center' => 'support#center', as: :center_support

    resources :markets, :only => :show, :constraints => MarketConstraint do
      resources :orders, :only => [:index, :destroy] do
        collection do
          post :clear
        end
      end
      resources :order_bids, :only => [:create] do
        collection do
          post :clear
        end
      end
      resources :order_asks, :only => [:create] do
        collection do
          post :clear
        end
      end
    end

    post '/pusher/auth', to: 'pusher#auth'

    resources :tickets, only: [:index, :new, :create, :show] do
      member do
        patch :close
      end
      resources :comments, only: [:create]
    end
  end

  post '/webhooks/tx' => 'webhooks#tx'
  post '/webhooks/eth' => 'webhooks#eth'
  draw :admin
  get '/admin/transaction' => 'admin/transaction#index', as: :admin_transaction
  get '/admin/withdrawal_request' => 'admin/withdrawal_request#index', as: :admin_withdrawal_request
  get '/admin/bonus' => 'admin/bonus#index', as: :admin_bonus
  get '/admin/penalty' => 'admin/penalties#index', as: :admin_penalty
  get '/admin/pending_deposits' => 'admin/pending_deposits#index', as: :admin_pending_deposits
  get '/admin/payment_system' => 'admin/payment_system#index', as: :admin_payment_system
  get '/admin/referral_setting' => 'admin/referral_setting#index', as: :admin_referral_setting
  get '/admin/security' => 'admin/security#index', as: :admin_security
  get '/admin/promos' => 'admin/promos#index', as: :admin_promos
  get '/admin/trade_history' => 'admin/trade_history#index', as: :admin_trade_history
  get '/admin/members_settings' => 'admin/members_settings#index', as: :admin_members_settings
  mount APIv2::Mount => APIv2::Mount::PREFIX

end

app/models/identity.rb
class Identity < OmniAuth::Identity::Models::ActiveRecord
  auth_key :email
  attr_accessor :old_password

  MAX_LOGIN_ATTEMPTS = 5

  validates :email, presence: true, uniqueness: true, email: true
  validates :password, presence: true, length: { minimum: 6, maximum: 64 }
  validates :password_confirmation, presence: true, length: { minimum: 6, maximum: 64 }

  before_validation :sanitize

  def increment_retry_count
    self.retry_count = (retry_count || 0) + 1
  end

  def too_many_failed_login_attempts
    retry_count.present? && retry_count >= MAX_LOGIN_ATTEMPTS
  end

  private

  def sanitize
    self.email.try(:downcase!)
  end

end

app/controllers/authentications/identities_controller.rb
module Authentications
  class IdentitiesController < ApplicationController
    before_action :auth_member!

    def new
      @identity = Identity.new(email: current_user.email)
    end

    def create
      identity = Identity.new(identity_params.merge(email: current_user.email))
      if identity.save && current_user.create_auth_for_identity(identity)
        redirect_to settings_path, notice: t('.success')
      else
        redirect_to new_authentications_identity_path, alert: identity.errors.full_messages.join(',')
      end
    end

    private

    def identity_params
      params.required(:identity).permit(:password, :password_confirmation)
    end

  end
end

app/controllers/identities_controller.rb
class IdentitiesController < ApplicationController
  before_filter :auth_anybody!, only: :new

  def new
    @identity = env['omniauth.identity'] || Identity.new
    @token = Token::ResetPassword.new
  end

  def edit
    @identity = current_user.identity
  end

  def update
    @identity = current_user.identity
    
    unless @identity.authenticate(params[:identity][:old_password])
      redirect_to edit_identity_path, alert: t('.auth-error') and return
    end

    if @identity.authenticate(params[:identity][:password])
      redirect_to edit_identity_path, alert: t('.auth-same') and return
    end

    if @identity.update_attributes(identity_params)
      current_user.send_password_changed_notification
      clear_all_sessions current_user.id
      reset_session
      redirect_to signin_path, notice: t('.notice')
    else
      render :edit
    end
  end

  def sendcode
    code_value = params[:code_value]
    phone_number = params[:phone_number]
    puts "BSDF"
    authkey = ENV['SMSAUTHKEY']
    sender  = ENV['SENDER']
    route   = ENV['ROUTE']
    country = ENV['COUNTRY']
    params = { :authkey => authkey, :mobiles => phone_number, :message => 'Your code is '+code_value, 
                 :sender => sender, :route => route, :country => country }
    puts URI.encode_www_form(params)
    res = Excon.get('http://api.msg91.com/api/sendhttp.php', :query => URI.encode_www_form(params))
    
    #res = Excon.get("http://api.msg91.com/api/sendhttp.php?authkey=188737AzwsuMr0F5a3893b2&mobiles=919999999990&message=Your%20otp%20is%20"+code_value+"&sender=Bitcharge&otp=2786&routes=4&country=0", true)
    puts res.body
    if res.status == 200
      res.body
    else
      Rails.logger.error(res.body)                          
      raise Errors::SMSNotSent, res.body
    end
    # xmlHttp.open("put", "http://api.msg91.com/api/sendhttp.php?authkey=188737AzwsuMr0F5a3893b2&mobiles=919999999990&message=Your%20otp%20is%20"+code_value+"&sender=Bitcharge&otp=2786&routes=4&country=0", true); // true for asynchronous 
    # xmlHttp.send(null)
    
    redirect_to signup_path
    # payload.symbolize_keys!

    # raise "TWILIO_NUMBER not set" if ENV['TWILIO_NUMBER'].blank?

    # puts "TWILIO Number TWilio"
    # # twilio_client.account.sms.messages.create(
    # #   from: ENV["TWILIO_NUMBER"],
    # #   to:   Phonelib.parse(payload[:phone]).international,
    # #   body: payload[:message]
    # # )
    # authkey = ENV['SMSAUTHKEY']
    # sender  = ENV['SENDER']
    # route   = ENV['ROUTE']
    # country = ENV['COUNTRY']
    # mobiles = Phonelib.parse(payload[:phone]).international
    # puts Phonelib.parse(payload[:phone]).national
    # puts Phonelib.parse(payload[:phone]).international
    # mobiles = mobiles.delete(' ')
    # raise ArgumentError, 'Please set authkey, sender, route && country for MSG91 API' unless authkey && sender && route && country

    # params = { :authkey => authkey, :mobiles => mobiles, :message => payload[:message], 
    #            :sender => sender, :route => route, :country => country }
    # puts URI.encode_www_form(params)
    # res = Excon.get('http://api.msg91.com/api/sendhttp.php', :query => URI.encode_www_form(params))
    # puts res.body
    # if res.status == 200
    #   res.body
    # else
    #   Rails.logger.error(res.body)                          
    #   raise Errors::SMSNotSent, res.body
    # end
  end

  private
  def identity_params
    params.required(:identity).permit(:password, :password_confirmation)
  end
end

app/views/identities/edit.html.slim
/= simple_form_for @identity do |f|
  = f.input :old_password
  = f.input :password
  = f.input :password_confirmation
  hr.split
  = f.button :wrapped, cancel: settings_path
.rb7.w-bg.mt20
  .settings-title.rel
    | change password
  .pl20.pr20.pt15.pb25
    .row
      = simple_form_for @identity do |f|
        .col-xs-8.mb12
          .fs13.t-up.mb12 current password:
          .row.form-line
            .col-xs-6
              input#identity_old_password.password.optional.acc-input name="identity[old_password]" placeholder=("Current password") type="password" /
          .fs13.t-up.mb12.mt20 new password:
          .row.form-line
            .col-xs-4
              input#identity_password.password.required.acc-input placeholder=("New password") name="identity[password]" type="password" /
            .col-xs-4
              input#identity_password_confirmation.password.required.acc-input placeholder=("Re-type new password") name="identity[password_confirmation]" type="password" /
          .green-but.w.mt25.w230
            .icon
            input.name style=("border:none;background:none;margin-left: 50px;")  cancel="/settings" data-loading-text="Updating..." name="commit" type="submit" value="SAVE PASSWORD" /
      .col-xs-4
        .info-box.v.fs12.lh20.mt5
          | Lorem ipsum dolor sit amet, consectetur adipiscing
          | elit. Donec ut porttitor lorem, eget fringilla enim.
          | Aenean iaculis ullamcorper euismod. Vestibulum
          | quis facilisis lectus. Ut vitae sagittis eros, ut sagittis
          | libero. Integer vestibulum neque nibh, nec
          | ullamcorper purus sollicitudin non.

app/views/identities/new.html.slim
/= simple_form_for @identity, :url => '/auth/identity/register' do |f|
  = f.input :email, :input_html => {:name => 'email', :autofocus => 'true'}
  = f.input :password, :input_html => {:name => 'password'}
  = f.input :password_confirmation, :input_html => {:name => 'password_confirmation'}
  
  #checkterm style="text-align:center"
    input type="checkbox" please tick box to confirm agreement with terms of service

  hr.split
  = f.button :wrapped, t('header.signup'), cancel: root_path

/= content_for :guide do
  ul.list-unstyled
    li: a href='#{signin_path}'= t('.signin')
.signup-page style=("height:100%;position:unset")
  .header
    .s-content
      .container-fluid
        .top-menu.row.ovh
          .col-xs-6.h75.ovh
            a.logo href="/" 
              img alt="" src=image_url("logo.png") /
          .col-xs-6.mt25.tac
            .fr
              a.tm-link href=""  Trading
              a.tm-link href=""  Exchange
              a.tm-link href=""  News
  .center-box
    .s-content
      .container-fluid
        .row
          .col-xs-1
          .col-xs-4
            .login-box.login-form-box.mt90
              .fs30.fw700.mb40.tac Access to account
              = render 'shared/flash'
              = simple_form_for @identity, :url => '/auth/identity/callback', :method => :post do |f|
                /input.acc-input.mb15 placeholder="E-mail" type="text" /
                input#identity_signin_email.string.email.required.form-control.acc-input.mb15 autofocus="autofocus" name="auth_key" placeholder=("E-mail Address") type="email" /

                /input.acc-input placeholder="Password" type="text" /
                input#identity_signin_password.password.required.form-control.acc-input name="password" placeholder="Password" type="password" /

                .cf.mt25
                  .fl
                    .green-but.w
                      .icon
                      .name
                        input cancel="/" data-loading-text="Creating..." name="commit" style=("width: 170px; margin-left: -40px; background:  none; border:  none;") type="submit" value=("LOGIN") /
                  .fr.mt10
                    a.tdu.g-color.login-control-but data-type="fp" href=''  Forgot password?
             
            .login-box.forgotpass-form-box.dn.mt90
              .fs30.fw700.mb40.tac Forgot password
              = render 'shared/flash'
              = simple_form_for @token, url: reset_passwords_path, as: :reset_password do |f|
                = f.input :email, input_html: {class:'acc-input'}
                .cf.mt25
                  .fl
                    .green-but.w
                      .icon
                      .name
                        input cancel="/signin" data-loading-text="Creating..." name="commit" style=("width: 170px; margin-left: -40px; background:  none; border:  none;") type="submit" value=("GET CODE") /
                  .fr.mt10
                    a.tdu.g-color.login-control-but data-type="lf" href=""  Return to login form
          .col-xs-2.tac.rel
            .v-line-sp-but
              .arr
            img alt="" src=image_url("v_line_sp.png") /
          .col-xs-4
            .signup-box.mt50
              .fs30.fw400.mb40.tac.t-w-color Create an account
              = simple_form_for @identity, :url => '/auth/identity/register' do |f|
                .form-group
                  .col-xs-6
                    input.signup-input placeholder=("First name") type="text" /
                  .col-xs-6
                    input.signup-input placeholder=("Second name") type="text" /
                = f.input :email, :input_html => {:name => 'email', :autofocus => 'true', class: 'signup-input'}
                = f.input :password, :input_html => {:name => 'password', class: 'signup-input'}
                = f.input :password_confirmation, :input_html => {:name => 'password_confirmation', class: 'signup-input'}
                .form-group
                  .col-xs-8.rel
                    .sp-get-code.dn onclick="send_code()" Get code 
                    input#phone_number.signup-input.signup-phone placeholder=("Enter phone") type="text" /
                  .col-xs-4
                    input.signup-input.sp-code-input.dn onkeyup="check_code(this.value)" placeholder=("Enter code") type="text" /
                .row.form-line.mt15
                  input#accept type="hidden" value="" /
                  .custom-checkbox.act data-input="accept" data-val="1" 
                    .icon
                    .txt I agree with the terms of the user agreement
                .tac.mt35
                  .green-but
                    .icon
                    .name
                      input#signup_btn cancel="/" data-loading-text="Creating..." name="commit" style=("width: 170px; margin-left: -20px;background:none;border:  none;\n") type="submit" value=("SIGNUP") 
            
            /= simple_form_for @identity, :url => '/auth/identity/register' do |f|
              .col-xs-6
                input.signup-input placeholder=("First name") type="text" /
              .col-xs-6
                input.signup-input placeholder=("Second name") type="text" /
              .form-group.mt15.email.required.identity_email.col-xs-12
                input.signup-input.required.email id="identity_email" name="email" autofocus="autofocus" placeholder="E-mail" type="email" /
              .col-xs-12.mt15.identity_password
                input.signup-input.required.password id="identity_password" name="password" placeholder="Password" type="password" /
              .col-xs-12.mt15.mb15.identity_password_confirmation
                input.signup-input.password.required id="identity_password_confirmation" name="password_confirmation" placeholder=("Retype password") type="password" /
              .col-xs-8.rel
                .sp-get-code.dn onclick="send_code()" Get code 
                input#phone_number.signup-input.signup-phone placeholder=("Enter phone") type="text" /
              .col-xs-4
                input.signup-input.sp-code-input.dn onkeyup="check_code(this.value)" placeholder=("Enter code") type="text" /
              .row.form-line.mt15
                input#accept type="hidden" value="" /
                .custom-checkbox.act data-input="accept" data-val="1" 
                  .icon
                  .txt I agree with the terms of the user agreement
              .tac.mt35
                .green-but
                  .icon
                  .name
                    input#signup_btn cancel="/" data-loading-text="Creating..." name="commit" style=("width: 170px; margin-left: -20px;background:none;border:  none;\n") type="submit" value=("SIGNUP") /
  .footer-sp
    |   © 2013 - 2017 BitCharge LLP. 160 Piccadilly, St. James's, London W1J 9EB, United Kingdom
javascript:
  var code_value = 0;
  document.getElementById("signup_btn").disabled = true;
  function send_code() {
    code_value = Math.floor(Math.random() * (9999 - 0 + 1)) + 0;
    phone_number =$("#phone_number").val();
    //console.log(phone_number);
    $.ajax({
      url: "/sendcode",
      type: 'post',
      data: { code_value: code_value, phone_number: phone_number }
    });
  }
  function check_code(code){
    console.log(code);
    if(code == code_value){
      document.getElementById("signup_btn").disabled = false;
      return 1;
    } else
      return 0;
  }
    